- name: To test first ansible
  hosts: all
  tasks:

  - name: Install a list of packages with a list variable
    yum:
        name: "{{ packages }}"
    vars:
        packages:
        - httpd
        - httpd-tools

  - name: Message
    ping: 
    

